all:
	erlc -o ../ebin zmq.erl
	erlc -o ../ebin zmq_subclient.erl
	erlc -o ../ebin zmq_pubserver.erl
	erlc -o ../ebin zmq_reqclient.erl
	erlc -o ../ebin zmq_repserver.erl

clean:
	rm -r ../ebin/*.beam
